export const mainColor = "#0057A0"; //dit is primary
export const secondaryColor = "#004A87";
export const colorRed = "#C62828";
export const colorGreen = "#388E3C";
export const colorOrange = "#ED6C02";
export const colorYellow = "#ffdf00";
export const colorPurple = "#800080";
export const disabledColor = "#d7d9d9";
export const backgroundColor = "#e8e8e8"; // grijs
export const mainColorSelected = "#edf4fb";
export const colorWhite = "#ffffff";